# Tensors


In [46]:
import torch
import numpy as np

## 1. Initializing a Tensor

Tensors can be initialized in various ways. Take a look at the following examples:

**Directly from data**

Tensors can be created directly from data. The data type is automatically inferred.



In [47]:
data = [[1, 2],[3, 4]]
# use torch.tensor() to convert this data to a tensor
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see `bridge-to-np-label`).



In [48]:
np_array = np.array(data)
# use torch.from_numpy() to convert this data to a tensor
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.



In [49]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

# assign a new datatype using dtype parameter
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1034, 0.1014],
        [0.6658, 0.2163]]) 



**With random or constant values:**

``shape`` is a **tuple** of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.



In [50]:
# (2,3,) , (2,3) and 2,3 are valid
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6586, 0.3578, 0.8365],
        [0.1515, 0.2240, 0.6234]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 2. Attributes of a Tensor

Tensor attributes describe their **shape**, **datatype**, and the **device** on which they are stored.



In [51]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 3. Operations on Tensors

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using
``.to`` method (after checking for GPU availability). 

In [52]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
elif torch.backends.mps.is_available():
    tensor = tensor.to("mps")

print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: mps:0


**Standard numpy-like indexing and slicing:**



In [53]:
tensor = torch.ones(4, 4)
print(f"tensor: \n{tensor}")
# two dimensional matric
print(f"First row: {tensor[0]}")
# : stands for all elements
print(f"First column: {tensor[:, 0]}")
# ... stands for all elements in all dimensions
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

tensor: 
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Joining tensors** You can use ``torch.cat`` to concatenate a sequence of tensors along a given dimension.
See also [torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html)_,
another tensor joining operator that is subtly different from ``torch.cat``.



In [54]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**Arithmetic operations**



In [55]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
# dot product
y1 = tensor @ tensor.T
print("1:",y1)
y2 = tensor.matmul(tensor.T)
print("2:",y2)

y3 = torch.rand_like(y1)
print("3:",y3)
torch.matmul(tensor, tensor.T, out=y3)
print("4:",y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
# element-wise product
z1 = tensor * tensor
print("5:",z1)
z2 = tensor.mul(tensor)
print("6:",z2)

z3 = torch.rand_like(tensor)
print("7:",z3)
torch.mul(tensor, tensor, out=z3)
print("8:",z3)

1: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
2: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
3: tensor([[0.7359, 0.6137, 0.2079, 0.6108],
        [0.3237, 0.2307, 0.2903, 0.4249],
        [0.4836, 0.1105, 0.6870, 0.6097],
        [0.6711, 0.8878, 0.6932, 0.3147]])
4: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
5: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
6: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
7: tensor([[0.6374, 0.0277, 0.0167, 0.0278],
        [0.4968, 0.8208, 0.3602, 0.4464],
        [0.1036, 0.4543, 0.5551, 0.1566],
        [0.7755, 0.2551, 0.1972, 0.7824]])
8: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Single-element tensors** If you have a one-element tensor, for example by aggregating all
values of a tensor into one value, you can convert it to a Python
numerical value using ``item()``:



In [56]:
agg = tensor.sum()
print(agg)
# use tensor.item() to get the value as a python number from a tensor containing a single value
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(12.)
12.0 <class 'float'>


notice that only one element tensors can be converted to Python scalars

In [57]:
t_1 = torch.ones(5)
# the following line will throw an error
# RuntimeError: a Tensor with 5 elements cannot be converted to Scalar
# t_1.item()

**In-place operations**
Operations that store the result into the operand are called in-place. They are denoted by a ``_`` suffix.
For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.



In [58]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])



## 4. Bridge with NumPy
Tensors on the CPU and NumPy arrays can **share their underlying memory
locations**, and **changing one will change	the other**.



### Tensor to NumPy array



In [59]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.



In [60]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy array to Tensor



In [61]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.



In [62]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


## 5. Other Tensor Operations
T stand for specific tensor
### `T.view()` or `torch.reshape()` -- Reshaping tensor 
Use `T.view()` method to change the shape of a tensor without changing its underlying data.

In [63]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Reshape the tensor
y = x.view(3, 2)
print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


Note that the total number of elements in the tensor must remain the same. Use "-1" to automatically infer the size of a particular dimension based on the other dimensions.

In [64]:
# The last dimension can be infered through the first dimension,
# since it's a two-dimensional tensor
y = x.view(2, -1)
print(y)

tensor([[1, 2, 3],
        [4, 5, 6]])


You can also use `torch.reshape()` which has the same functionality, but can be used as a function as well as a method.

In [65]:
y = torch.reshape(x, (3, 2))
print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


### `torch.argmax()` -- Find the index of the maximum value
Use `torch.argmax()` to find the index of the maximum value of a tensor.

Parameters:
- input (Tensor) – the input tensor.

- dim (int) – the dimension to reduce. If None, the argmax of the flattened input is returned.

- keepdim (bool) – whether the output tensor has dim retained or not. Ignored if dim=None.

In [66]:
a = torch.randn(4,4)
print(a)

tensor([[ 0.5827,  0.4513, -0.3963, -1.1931],
        [ 1.8570, -0.1275,  0.7349,  0.4797],
        [-0.2405, -0.3073, -0.6663, -0.9125],
        [ 0.3198, -1.0983,  0.1439,  1.0674]])


In [67]:
print(torch.argmax(a))
# dim = 0: find the maximum value in each column
print(torch.argmax(a, dim=0))
# dim = 1: find the maximum value in each row
print(torch.argmax(a, dim=1))

tensor(4)
tensor([1, 0, 1, 3])
tensor([0, 0, 0, 3])


### `torch.argsort()` -- Returns the indices that sort a tensor along a given dimension

Parameters:
- input (Tensor) – the input tensor.

- dim (int, optional) – the dimension to sort along

- descending (bool, optional) – controls the sorting order (ascending or descending). Default: False

- stable (bool, optional) – controls the relative order of equivalent elements

In [68]:
a = torch.randn(4, 4)
print(a)
# argsort along columns
print(torch.argsort(a, dim=0))
# argsort along rows
print(torch.argsort(a, dim=1))
# argsort along columns in descending order
print(torch.argsort(a, dim=0, descending=True))

tensor([[-0.7889,  0.3980,  0.1023, -0.8025],
        [-0.6876, -0.3441,  1.5822,  0.9872],
        [ 0.9006, -0.1714,  0.0850,  1.6516],
        [ 1.9089,  0.3430, -0.0823,  0.2357]])
tensor([[0, 1, 3, 0],
        [1, 2, 2, 3],
        [2, 3, 0, 1],
        [3, 0, 1, 2]])
tensor([[3, 0, 2, 1],
        [0, 1, 3, 2],
        [1, 2, 0, 3],
        [2, 3, 1, 0]])
tensor([[3, 0, 1, 2],
        [2, 3, 0, 1],
        [1, 2, 2, 3],
        [0, 1, 3, 0]])


### `T.backword()` -- Compute gradient of current tensor w.r.t. graph leaves.

### `torch.split()` -- Split tensor into chunks

Parameters:
- tensor (Tensor) – tensor to split.

- split_size_or_sections (int) or (list(int)) – size of a single chunk or list of sizes for each chunk. 
  <br>
  If split_size_or_sections is an integer type, then tensor will be split into equally sized chunks (if possible). Last chunk will be smaller if the tensor size along the given dimension dim is not divisible by split_size. If split_size_or_sections is a list, then tensor will be split into len(split_size_or_sections) chunks with sizes in dim according to split_size_or_sections.

- dim (int) – dimension along which to split the tensor.

Return type:
- List[Tensor]

In [69]:
# torch.arange(): return a 1-D tensor of size [end-start] with values from the interval [start, end)
a = torch.arange(10).reshape(5, 2)
print(a)
print(torch.split(a, 2))
print(torch.split(a, [1, 4]))

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
(tensor([[0, 1],
        [2, 3]]), tensor([[4, 5],
        [6, 7]]), tensor([[8, 9]]))
(tensor([[0, 1]]), tensor([[2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))


### `torch.squeeze()` -- Returns a tensor with all the dimensions of input of size 1 removed.

For example, if input is of shape: (A×1×B×C×1×D) then the out tensor will be of shape: (A×B×C×D) .

When dim is given, a squeeze operation is done only in the given dimension. If input is of shape: (A×1×B) , squeeze(input, 0) leaves the tensor unchanged, but squeeze(input, 1) will squeeze the tensor to the shape (A×B) .

Parameters:
- input (Tensor) – the input tensor.

- dim (int or tuple of ints, optional) –

    if given, the input will be squeezed
only in the specified dimensions.

*Note*: The returned tensor shares the storage with the input tensor, so changing the contents of one will change the contents of the other.

In [70]:
x = torch.zeros(2, 1, 2, 1, 2)
print(x.size())
print(torch.squeeze(x).size())
print(torch.squeeze(x, 0).size())
print(torch.squeeze(x, 1).size())
# dim parameter can also be a tuple
print(torch.squeeze(x, (1,2,3)).size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])
torch.Size([2, 2, 2])


### `torch.unsqueeze()` -- Returns a new tensor with a dimension of size one inserted at the specified position.

torch.unsqueeze(input, dim) → Tensor
parameters:
- input (Tensor) – the input tensor.
- dim(int) – the index at which to insert the singleton dimension

In [79]:
x = torch.tensor([1, 2, 3, 4])
# equal to torch.unsqueeze(x, 0)
print(x.unsqueeze(0))
print(x.unsqueeze(1))
print(x.unsqueeze(-1))

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1],
        [2],
        [3],
        [4]])


### `torch.map()` -- Applies a function to each element in the tensor.

When we want to apply the same callable to a tensors, we can use `torch.map()`.

In [73]:
def f(a):
    return a*a
t = torch.tensor([1, 2, 3])
r = map(f, t)
# return a iterator
for i in r:
    print(i)

tensor(1)
tensor(4)
tensor(9)
